name: "Build Godot Action"
description: "Build a Godot project for multiple platforms"
author: "mlm-games"

inputs:
  # BINARY_NAME:
  #   description: 'Name of the exported binary'
  #   required: true
  EXPORT_PRESET_NAME:
    description: 'Name of the preset in `export_presets.cfg` to use'
    required: true
  GODOT_VER:
    description: 'Godot version to use, uses latest Godot 4.x release by default. (e.g. 4.2.1-stable)'
    required: false
    default: ''
  # PACKAGE:
  #   description: 'Set true to output an artifact zip file'
  #   default: false
  PROJECT_DIR:
    description: 'Location of Godot project in repository'
    default: "."
  DEBUG_MODE:
    description: 'Whether or not to use `--export-debug`'
    default: false
  GODOT_PREVIEW_BUILDS:
    description: 'Use godot preview builds'
    default: false
  BUTLER_UPLOAD:
    description: 'Upload to itch.io using butler'
    default: false
  # BUTLER_UPLOAD_CHANNEL:
  #   description: 'Channel to upload to itch.io using butler'
  #   default: "windows"
  BUTLER_CREDENTIALS:
    description: 'butler credentials'
    default: "windows"
  ITCH_USER_SLASH_GAME:
    description: 'Your username and gamename in the format of "user/game"'
    default: ''
  RELEASE_KEYSTORE:
    description: 'Your release keystore'
    default: ''
  KEYSTORE_PASSPHRASE:
    description: 'the passphrase used to encrypt the keystore'
    default: ''
  KEY_ALIAS:
    description: 'Your game signing key alias'
    default: ''
  KEY_PASSWORD:
    description: 'Signing key password'
    default: ''
    

outputs:
  build:
    description: 'Path to the build output directory'
    value: ${{ steps.export.outputs.build }}

runs:
  using: "composite"
  steps:
    - name: Get Godot version
      id: version
      shell: bash
      run: |
        if [ -z "${{ inputs.GODOT_VER }}" ]; then
          if [ "${{ inputs.GODOT_PREVIEW_BUILDS }}" == "true" ]; then
            # Get latest Godot 4.x release version from GitHub API
            LATEST_VER=$(curl -s https://api.github.com/repos/godotengine/godot-builds/releases | grep -oP '"tag_name": "\K[^"]+' | grep '^4\.' | head -n 1 )
          else
            # Get latest Godot 4.x preview version from GitHub API
            LATEST_VER=$(curl -s https://api.github.com/repos/godotengine/godot/releases | grep -oP '"tag_name": "\K[^"]+' | grep '^4\.' | head -n 1 )
          fi
            echo "GODOT_VERSION=${LATEST_VER}" >> $GITHUB_OUTPUT
        else
          echo "GODOT_VERSION=${{ inputs.GODOT_VER }}" >> $GITHUB_OUTPUT
        fi

    - name: Create directories
      shell: bash
      run: |
        mkdir -p ~/.local/share/godot/export_templates/$(echo ${{ steps.version.outputs.GODOT_VERSION }} | sed 's/[^a-zA-Z0-9_]/./g')
        mkdir -p ~/godot-binary 

    - name: Download Godot
      shell: bash
      run: |
        GODOT_BASENAME="Godot_v${{ steps.version.outputs.GODOT_VERSION }}_linux.x86_64"
        if [ "${{ inputs.GODOT_PREVIEW_BUILDS }}" == "true" ]; then
            wget -q "https://github.com/godotengine/godot-builds/releases/download/${{ steps.version.outputs.GODOT_VERSION }}/${GODOT_BASENAME}.zip" -O ~/godot-binary/godot.zip
        else
            wget -q "https://github.com/godotengine/godot/releases/download/${{ steps.version.outputs.GODOT_VERSION }}/${GODOT_BASENAME}.zip" -O ~/godot-binary/godot.zip
        fi
        unzip -q ~/godot-binary/godot.zip -d ~/godot-binary
        chmod +x ~/godot-binary/${GODOT_BASENAME}
        mv ~/godot-binary/${GODOT_BASENAME} ~/godot-binary/godot

    - name: Download and install export templates
      shell: bash
      run: |
        TEMPLATES_BASENAME="Godot_v${{ steps.version.outputs.GODOT_VERSION }}_export_templates"
        wget -q "https://github.com/godotengine/godot-builds/releases/download/${{ steps.version.outputs.GODOT_VERSION }}/${TEMPLATES_BASENAME}.tpz" -O ~/templates.tpz
        unzip -q ~/templates.tpz -d ~/.local/share/godot/export_templates/temp
        mkdir -p ~/.local/share/godot/export_templates/$(echo ${{ steps.version.outputs.GODOT_VERSION }} | sed 's/[^a-zA-Z0-9_]/./g')
        mv ~/.local/share/godot/export_templates/temp/templates/* ~/.local/share/godot/export_templates/$(echo ${{ steps.version.outputs.GODOT_VERSION }} | sed 's/[^a-zA-Z0-9_]/./g')/

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: ''
    - name: Setup Android SDK
      if: contains(inputs.EXPORT_PRESET_NAME, 'Android') #TODO: implement a better way?
      shell: bash
      run: |        
       sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "build-tools;34.0.0" "platforms;android-34" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;23.2.8568313"        
        
       ~/godot-binary/godot --headless --import

        export GODOT_CFG=$(ls ~/.config/godot/editor_settings-*.tres)
        sed -i -e "s:\(^.*java_sdk_path\)\s*=.*$:\1 = "$JAVA_PATH":" $GODOT_CFG
        sed -i -e "s:\(^.*android_sdk_path\)\s*=.*$:\1 = "$ANDROID_SDK_ROOT":" $GODOT_CFG


    - name: Decode Keystore
      if: inputs.RELEASE_KEYSTORE != ''
      shell: bash
      run: |
        echo "${{ inputs.RELEASE_KEYSTORE }}" > release.keystore.asc
        gpg -d --passphrase "${{ inputs.KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > release.keystore
        echo "Keystore created in path $(find ~ -name "release.keystore" -print) ."

    - name: Insert keystore values
      if: inputs.RELEASE_KEYSTORE != ''
      shell: bash
      run: |
        export GODOT_ANDROID_KEYSTORE_RELEASE_PATH=$(find ~ -name "release.keystore" -print)
        export GODOT_ANDROID_KEYSTORE_RELEASE_USER=${{ inputs.KEY_ALIAS }}
        export GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD=${{ inputs.KEY_PASSWORD }}
        
    - name: Export project
      id: export
      shell: bash
      run: |
        # Set export mode
        mode="export-release"
        if [ "${{ inputs.DEBUG_MODE }}" = "true" ]; then
          echo "Exporting in debug mode!"
          mode="export-debug"
        fi

        # Set build path
        BUILD_PATH="${GITHUB_WORKSPACE}/${{ inputs.PROJECT_DIR }}/builds/"
        echo "build=${BUILD_PATH}" >> $GITHUB_OUTPUT

        export GODOT_ANDROID_KEYSTORE_RELEASE_PATH=$(find ~ -name "release.keystore" -print)
        export GODOT_ANDROID_KEYSTORE_RELEASE_USER=${{ inputs.KEY_ALIAS }}
        export GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD=${{ inputs.KEY_PASSWORD }}
        
        # Export project
        echo "Building for ${{ inputs.EXPORT_PRESET_NAME }}"
        cd "${GITHUB_WORKSPACE}/${{ inputs.PROJECT_DIR }}"
        echo "version_name=$(grep 'version/name=' export_presets.cfg | head -1 | awk -F'"' '{print $2}')" >> $GITHUB_ENV
        echo "version_code=$(grep 'version/code=' export_presets.cfg | head -1 | awk -F'=' '{print $2}')" >> $GITHUB_ENV
        mkdir -p builds/osx/
        mkdir builds/web/
        ~/godot-binary/godot --headless --${mode} "${{ inputs.EXPORT_PRESET_NAME }}"
        echo "Build Done"
                
    - name: Upload using butler
      if: inputs.BUTLER_UPLOAD == 'true'
      shell: bash
      run: |
        if [ -n "${{ env.version_name }}" ]; then
          version_arg="--userversion ${{ env.version_name }}"
        else
          version_arg=""
        fi
    
        curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        
        cat ${{ inputs.BUTLER_CREDENTIALS }} >> ~/.config/itch/butler_creds
        
        # Get export paths and upload each existing file
        export_paths=($(grep 'export_path=' export_presets.cfg | awk -F'=' '{print $2}' | tr -d '"'))
        
        for path in "${export_paths[@]}"; do
            if [ -f "$path" ]; then
                echo "Found exported file: $path"
                
                # Determine the channel based on the file path/name
                channel=""
                case "$path" in
                    *"web"*|*"html")
                        channel="web"
                        web_dir=$(dirname "$path")
                        cd "$web_dir"
                        zip -r web.zip *
                        mv web.zip ../
                        cd ..
                        path="web.zip"
                        ;;
                    *"windows"*|*".exe") channel="windows" ;;
                    *"linux"*"x86_64") channel="linux" ;;
                    *"linux"*"aarch64"*|*"arm64") channel="linux-arm64" ;;
                    *"android"*"apk") channel="android" ;;
                    *"dmg.zip") channel="macos" ;;
                    *) echo "Unknown platform for $path" ; continue ;;
                esac
    
                # Upload to itch.io
                echo "Uploading to channel: $channel"
                ./butler push "$path" "${{ inputs.ITCH_USER_SLASH_GAME }}:$channel" $version_arg
            else
                echo "File not found: $path"
            fi
        done


branding:
  icon: loader
  color: blue
